export const SET_R_USER_EMAIL = 'SET_R_USER_EMAIL';
export const UPDATE_R_VALIDATION = 'UPDATE_R_VALIDATION';
export const SET_R_USER_PASSWORD = 'SET_R_USER_PASSWORD';
export const SET_USER_C_PASSWORD = 'SET_USER_C_PASSWORD';
