// AUTH STATE
export const LOGOUT = 'LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// MOMENT STATE
export const SET_MOMENT = 'SET_MOMENT';
export const SET_MOMENTS = 'SET_MOMENTS';
export const CLEAR_MOMENT = 'CLEAR_MOMENT';
export const SET_RANGE_ID_SELECTED = 'SET_RANGE_ID_SELECTED';
export const SET_IS_MOMENT_IN_RANGE = 'SET_IS_MOMENT_IN_RANGE';
